Complete support for French, Spanish and German.
aaaton/golem pull request #5
Opened 2018-12-27 21:37 UTC by charlesgiroux

The switch statement for locale was missing options for French, Spanish and German.

- Added French, Spanish and German to switch statement.

- Added tests for French, Spanish and German.

2019-01-09 10:57 UTC, aaaton commented
Thank you! This is neat, but the local imports are referencing your fork `"github.com/charlesgiroux/golem/dicts"` instead of the main repo `"github.com/aaaton/golem/dicts", 

Here is a nice, short article of better forking with go: https://dev.to/loderunner/working-with-forks-in-go-3ab6

But since you're already done, maybe you could just swap back the imports to aaaton, and commit again?

2019-01-09 10:57 UTC, aaaton requested changes

2019-01-09 10:57 UTC, aaaton commented on main.go
> -	"github.com/aaaton/golem/dicts"
here

2019-01-09 10:57 UTC, aaaton commented on main_test.go
> -	"github.com/aaaton/golem/dicts"
and here

2019-01-15 21:16 UTC, charlesgiroux commented
Yes for sure! I'll look into doing that during the week.

2019-02-18 08:58 UTC, merged

2019-02-18 08:59 UTC, aaaton commented
Thank you for your PR!